---
# default site settings
# configure these values for your project
project:
  name: "Halo Wars: Definitive Edition Modding Docs"

collections:
  guides:
    output: true
    permalink: "/:collection/:path/"
    title: Guides
    tab-order: 1
  wiki:
    output: true
    permalink: "/:collection/:path/"
    title: Wiki
    tab-order: 2
  tools:
    output: true
    permalink: "/:collection/:path/"
    title: Tools
    tab-order: 3

highlighter: rouge
permalink: pretty
sass:
  style: compressed

plugins:
  - jemoji
  - jekyll-remote-theme
remote_theme: pixeldroid/programming-pages
