---
# default site settings
# configure these values for your project
project:
  name: "Halo Wars: Definitive Edition Modding Docs"

collections:
  guides:
    output: true
    permalink: "/guides/:path/"
    title: Guides
    tab-order: 1
  docs:
    output: true
    permalink: "/docs/:path/"
    title: Docs
    tab-order: 2
  examples:
    output: true
    permalink: "/tools/:path/"
    title: Tools
    tab-order: 3

highlighter: rouge
permalink: pretty
sass:
  style: compressed

plugins:
  - jemoji
  - jekyll-remote-theme
remote_theme: pixeldroid/programming-pages
